<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Login</name>
   <tag></tag>
   <elementGuidId>a51a3709-64ea-4a72-9171-0a61478861b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@data-automation='Login'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sx2jih0.zcydq85y.zcydq8p.zcydq85a.zcydq84u.zcydq8y.zcydq8x.zcydq85.zcydq8g2.zcydq84.zcydq8h._97fi8d0._97fi8d5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f867b60-9459-4ef2-b66d-226d6da2c09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>646852e3-a420-42b9-9760-61c2af87c25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>1d4427fa-1757-4630-8be4-b224aced4f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>1446119f-2e75-4d76-b897-1b67e58b1b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq85y zcydq8p zcydq85a zcydq84u zcydq8y zcydq8x zcydq85 zcydq8g2 zcydq84 zcydq8h _97fi8d0 _97fi8d5</value>
      <webElementGuid>943d1cae-2c28-460d-9bf4-5c8b91eedede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://myjobstreet.jobstreet.com.sg/home/login.php?site=sg&amp;language_code=3</value>
      <webElementGuid>96a1bab2-d0cd-42f7-9e7e-8d8a8a937454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>e337787b-9fed-4a4f-af73-28899d7e03d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@data-automation='Login'])[1]</value>
      <webElementGuid>61a187f1-e75a-45bc-9a84-59779c56d468</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div/div/div/div[2]/div[2]/div/div/div/div/div/a</value>
      <webElementGuid>4388e17a-b0cb-4e16-b066-41874da1356d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/following::a[1]</value>
      <webElementGuid>15642fe5-7dc5-4c68-bf40-65221302f9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career advice'])[1]/following::a[1]</value>
      <webElementGuid>3cc9b83c-039d-4617-af2b-a7151f35ef02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For employers'])[1]/preceding::a[1]</value>
      <webElementGuid>d77b5aa9-c34a-41a3-a354-a57ddd845d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://myjobstreet.jobstreet.com.sg/home/login.php?site=sg&amp;language_code=3')])[2]</value>
      <webElementGuid>9b1584d9-e76c-4c34-b1be-377dac8aa52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a</value>
      <webElementGuid>1f486539-a836-4cb5-9ba8-9ea20a34a286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Login' and @href = 'https://myjobstreet.jobstreet.com.sg/home/login.php?site=sg&amp;language_code=3' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>a5d2be9a-b0f4-463d-8b7c-b1a1a52eb5de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
