<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-Home</name>
   <tag></tag>
   <elementGuidId>a97abdf7-6676-4bcb-84d8-2d0c356e53f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header_home_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header_home_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b34dda60-c286-446b-8a99-ba71ef2c258c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header_home_link</value>
      <webElementGuid>e76b8a5a-558f-4ff3-b359-4ca2753ba5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.jobstreet.com.my</value>
      <webElementGuid>387fa23f-6e02-474e-ac4a-e1867ac3c8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>_gaq.push(['_trackEvent', 'JSMY Personalized Homepage', 'Homepage clicked', 'New Header']);</value>
      <webElementGuid>809b8e2d-e334-4ad0-bb28-7523ce04d4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Leading Job Site in Malaysia - Find Jobs in Malaysia</value>
      <webElementGuid>cb1241a9-c166-4f3e-b58a-28bfb706b7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>64366973-56d5-46fb-8a9c-460cc2a17c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='header_home_link']</value>
      <webElementGuid>250e1451-82c8-4d44-b0dd-3246ab2de83e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='header_home_link']</value>
      <webElementGuid>1c115b32-b432-41d1-9c96-7166dd98a9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobile_search_bar_menu']/ul/li/a</value>
      <webElementGuid>d4db0e00-96d6-4311-b2e8-e4a556be0950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home')]</value>
      <webElementGuid>31685ba4-e06e-4ccf-8cb8-cebebd96e9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[1]</value>
      <webElementGuid>99f666be-e976-4745-8dca-5784ec0bee5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Jobs'])[1]/preceding::a[1]</value>
      <webElementGuid>82fd2778-5712-4eed-92ae-fab7f3ec4fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyJobStreet'])[1]/preceding::a[2]</value>
      <webElementGuid>9acf8a1d-48d4-4481-9705-a00ebf1452a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>d2b1f6e9-0aab-4a25-ae4d-b977cc7ab848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.jobstreet.com.my')]</value>
      <webElementGuid>f7f0498f-460a-474f-b549-a804da9efb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>822215ba-6137-41d4-91e1-5d7834534579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'header_home_link' and @href = 'https://www.jobstreet.com.my' and @title = 'Leading Job Site in Malaysia - Find Jobs in Malaysia' and (text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>0ef43908-af44-4e60-8e2c-9b78b9a03f22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
