<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-Logout</name>
   <tag></tag>
   <elementGuidId>602440e7-c2bb-49be-8b02-f5ec456f7c7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@data-automation='Logout'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sx2jih0.sx2jihf.sx2jih0._1aq6jw0._18qlyvc22.zcydq89i.zcydq88i.zcydq84u.zcydq8p.zcydq8h.zcydq8fy.zcydq85._18qlyvc14._18qlyvc17._18qlyvc18._18qlyvc1h.zcydq81s.zcydq82h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c7c7d74f-16b1-4e0f-bbd7-29093c8d73d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>4a5308fd-443e-45eb-8acc-1b252bb74953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2edabbd2-10f4-41de-840d-ca4c385d195c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>384f0741-9f60-4375-8ca4-4dd420fcef7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jihf sx2jih0 _1aq6jw0 _18qlyvc22 zcydq89i zcydq88i zcydq84u zcydq8p zcydq8h zcydq8fy zcydq85 _18qlyvc14 _18qlyvc17 _18qlyvc18 _18qlyvc1h zcydq81s zcydq82h</value>
      <webElementGuid>95fd5121-ee5b-4881-be41-71c69c59c10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://myjobstreet.jobstreet.com.sg/home/logout.php</value>
      <webElementGuid>e6dd1cd4-5cf0-49a4-a66a-5e4465639fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>fcc49dd3-e64f-495f-8846-81abd7e929ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@data-automation='Logout'])[1]</value>
      <webElementGuid>de6ca4b4-7935-40ad-8a76-d28cf90eca50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div/div/div/div[2]/div[2]/div/div/div/div/div[2]/div/a[3]</value>
      <webElementGuid>00064d93-0ad7-45de-bcdc-99fd8972b858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job applications'])[1]/following::a[1]</value>
      <webElementGuid>f0b8e80d-3657-4297-aeb3-2453d826cf0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View profile'])[1]/following::a[2]</value>
      <webElementGuid>0068ca44-9184-4783-8cf0-f17bbc599630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For employers'])[1]/preceding::a[1]</value>
      <webElementGuid>943f65cd-7833-44c6-a54f-1db2e58114f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://myjobstreet.jobstreet.com.sg/home/logout.php')]</value>
      <webElementGuid>58a1be6b-8cdf-493f-abb3-af984b0c8a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/a[3]</value>
      <webElementGuid>4011245e-99ab-44df-8726-39e5f91dd5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://myjobstreet.jobstreet.com.sg/home/logout.php' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>309ee160-715c-4ed6-bdd8-de8b20b4538c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
