<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-MyJobStreet</name>
   <tag></tag>
   <elementGuidId>281b913d-d2e3-4fe6-9fb1-74c25e157f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@data-automation='MyJobStreet'])[1] | //a[@id='header_myjobstreet_link']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//a[@data-automation='MyJobStreet'])[1] | //a[@id='header_myjobstreet_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4f5d9b67-621d-480b-a260-5cbdaad7fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq856 zcydq8ea zcydq8n zcydq85a zcydq8d2 rdmf22</value>
      <webElementGuid>59f63ffb-038c-4fc2-9d7d-3e87ac2b1698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MyJobStreet</value>
      <webElementGuid>57256fa9-8e96-4d0a-be7b-84436ae9273d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@data-automation='MyJobStreet'])[1] | //a[@id='header_myjobstreet_link']</value>
      <webElementGuid>2cab877b-f891-491c-8fc4-0411d1dae472</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div/div/div/div/div[2]/div/a[2]/span</value>
      <webElementGuid>2beb32d8-bc82-49ef-b859-717cefc3114d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job search'])[1]/following::span[1]</value>
      <webElementGuid>820e0af2-7354-4b50-8573-c3caf28f840d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JobStreet'])[1]/following::span[4]</value>
      <webElementGuid>523817b3-13f2-4683-aa7e-61b451c58a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company profiles'])[1]/preceding::span[3]</value>
      <webElementGuid>a7479ca3-bf74-4592-9abe-c5dd32bfebcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>33b02d5a-588f-48ff-889f-72e975bd24a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MyJobStreet' or . = 'MyJobStreet')]</value>
      <webElementGuid>fbc59b0a-7676-49be-9cfa-46ad2df13d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
