<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-MyJobStreet</name>
   <tag></tag>
   <elementGuidId>281b913d-d2e3-4fe6-9fb1-74c25e157f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@data-automation='MyJobStreet'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f56200ae-4505-4e6f-b864-892dd6cb5605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq856 zcydq8ea zcydq8n zcydq85a zcydq8d2 rdmf22</value>
      <webElementGuid>d3592ad2-5f31-4e9c-994b-fc5c851e9ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MyJobStreet</value>
      <webElementGuid>e17792dd-268c-4cc7-b1c3-1e0a6856944a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@data-automation='MyJobStreet'])[1]</value>
      <webElementGuid>6c37880e-df59-4894-a92b-1020e21af816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[3]/div/div/div/div/div[2]/div/a[2]/span</value>
      <webElementGuid>2e92b350-530c-4c76-b605-808fa4795344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job search'])[1]/following::span[1]</value>
      <webElementGuid>5b756b59-a750-46d7-b874-724999c7d421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JobStreet'])[1]/following::span[4]</value>
      <webElementGuid>613d069c-429f-44b8-951b-0cfb9b6f2688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company profiles'])[1]/preceding::span[3]</value>
      <webElementGuid>3f33189e-783a-458d-9cf7-f628c55e3bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>4ffdb902-11aa-423f-9b1d-2723af6999d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MyJobStreet' or . = 'MyJobStreet')]</value>
      <webElementGuid>ef45b40b-136a-407f-9106-b62ce3c03d1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
