<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Sort-By</name>
   <tag></tag>
   <elementGuidId>0a6e151a-b2dc-49de-8136-3a65985857c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-automation='SortByButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sx2jih0.zcydq84u._18qlyvc0._18qlyvc1x._18qlyvc3._18qlyvc4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cee08040-f11c-460d-b0f9-f60ea7c4f689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq84u _18qlyvc0 _18qlyvc1x _18qlyvc3 _18qlyvc4</value>
      <webElementGuid>d3b257da-046f-44ce-ad28-d3c26764f22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Relevance</value>
      <webElementGuid>341cabb7-3583-46fa-bc0c-4c317f3e3668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-automation='SortByButton']</value>
      <webElementGuid>31974024-3a53-491b-b345-129d1d11ed75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='srpSearchForm']/div/div/form/div/div[2]/div/div/div/div[2]/div/div/button/div[3]/span</value>
      <webElementGuid>5d522574-d536-464b-9d77-437151d46a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/following::span[1]</value>
      <webElementGuid>9c843ac5-2298-42c3-b999-b4cb812f7a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::span[2]</value>
      <webElementGuid>9119779a-2db7-488e-80b1-b442ab0deacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Searches related to qa automation jobs'])[1]/preceding::span[1]</value>
      <webElementGuid>431e30d7-3a28-48e9-8ad7-31972c7028b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qa engineer jobs'])[1]/preceding::span[1]</value>
      <webElementGuid>42452e40-5f52-4069-999a-3b6f8afd5614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Relevance']/parent::*</value>
      <webElementGuid>5aa3017f-554b-4425-8e2d-814e08eda711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div[3]/span</value>
      <webElementGuid>a5365491-0219-47db-8f62-04b8d45ef456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Relevance' or . = 'Relevance')]</value>
      <webElementGuid>c9c9ea4f-ca56-4922-a9ad-9bcacc78ed4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
