<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-filter-Salary</name>
   <tag></tag>
   <elementGuidId>dc167074-fbce-48a7-86e0-4d9902671d6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-automation='salaryFilterButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sx2jih0.sx2jih7.zcydq85y.zcydq8p.zcydq85a.zcydq84u.zcydq8y.zcydq8x.zcydq85.zcydq8g2.zcydq84.zcydq8h._97fi8d0._16ycv5p0._16ycv5p1._97fi8d6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9589a0df-d2b9-4fb1-998f-d51e2e2d68cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih7 zcydq85y zcydq8p zcydq85a zcydq84u zcydq8y zcydq8x zcydq85 zcydq8g2 zcydq84 zcydq8h _97fi8d0 _16ycv5p0 _16ycv5p1 _97fi8d6</value>
      <webElementGuid>cc880387-f8f0-4317-858b-77aedf7c3703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a35c554-5051-4118-83f7-71f44d992009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>salaryFilterButton</value>
      <webElementGuid>4aa69718-2013-4d5c-8b30-685aff64add7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salary</value>
      <webElementGuid>4e37e09c-3c3e-456b-8a3b-5dfdd3dbdfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-automation='salaryFilterButton']</value>
      <webElementGuid>48e20d50-4bbc-4c11-986e-db291870a18f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>8f274b3e-1a74-4e99-8366-db5389aff9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='srpSearchForm']/div/div/form/div/div[2]/div/div/div/div/div/div/div/div/div/button</value>
      <webElementGuid>d9988b47-6dec-49e6-9a62-4cbccf7f3168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[1]</value>
      <webElementGuid>b1df9c6a-0783-4fb2-9f67-1c0dc47b5766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Job Specializations'])[1]/following::button[2]</value>
      <webElementGuid>9d6f650f-53c1-4ad9-8909-ee14fbca57c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job type'])[1]/preceding::button[1]</value>
      <webElementGuid>073cd1da-e45d-4636-8af9-35cfd11eb4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div/div/div/div/div/div/div/button</value>
      <webElementGuid>7dbcc711-30d5-448a-9e73-3de885fd407f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Salary' or . = 'Salary')]</value>
      <webElementGuid>05d530e3-5737-4378-bc01-def9c0623bff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
