<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-filter-Job type</name>
   <tag></tag>
   <elementGuidId>ecb367e3-9ff8-4495-a411-62a804a1cd2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-automation='jobTypeFilterButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1a87cb4-85cc-4fb1-ad6a-aa31671c92b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih7 zcydq85y zcydq8p zcydq85a zcydq84u zcydq8y zcydq8x zcydq85 zcydq8g2 zcydq84 zcydq8h _97fi8d0 _16ycv5p0 _16ycv5p1 _97fi8d6</value>
      <webElementGuid>3eb1602d-410e-4023-9fb7-61135e04c074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>298e74c1-4d67-4d58-a9cc-884e0c1c3172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>jobTypeFilterButton</value>
      <webElementGuid>b0c8c151-f0d7-454f-a920-dbc669b606e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job type</value>
      <webElementGuid>82d3048a-8cd0-493e-8f0c-129ef4fef929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-automation='jobTypeFilterButton']</value>
      <webElementGuid>9870c71b-3211-4240-a749-6ea40d00ae35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>8e066acb-0635-4ce0-abc7-ecbf61194850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='srpSearchForm']/div/div/form/div/div[2]/div/div/div/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>9f1afbff-694d-4cf8-94cc-9cc7bc2e5d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salary'])[1]/following::button[1]</value>
      <webElementGuid>a11dc5dd-8db9-424e-9c93-b2b57cc5a593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[2]</value>
      <webElementGuid>9ec7fbcc-1c63-4763-a149-b9782de71676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date posted'])[1]/preceding::button[1]</value>
      <webElementGuid>e438846c-fcfe-45d4-b006-025f2916d591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>7829ad30-fd4a-4a2c-93a2-4e30fb712af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Job type' or . = 'Job type')]</value>
      <webElementGuid>b7bdc68b-9162-4a44-8cad-f8781a5ef489</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
