<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-Testimonials</name>
   <tag></tag>
   <elementGuidId>c4d43beb-5944-4fc2-8fa6-3f5e445f4010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-automation='Testimonials']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bccd805c-91a7-4cf9-99ea-60156c3c8fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 rxszx01</value>
      <webElementGuid>3994589e-3b28-4c7d-81e2-b2da0c5ab8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testimonials</value>
      <webElementGuid>9b2a2b03-2280-4765-b92d-e582ff90ca40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@data-automation='Testimonials']/div</value>
      <webElementGuid>8b60c85b-c14d-42f6-95e6-60d6afe75c1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[5]/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div[6]/a/div/span/span</value>
      <webElementGuid>095c4645-acbe-4168-b8c1-c1d7b47fc7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore careers'])[1]/following::span[2]</value>
      <webElementGuid>984f69a8-26c6-4631-a484-6d1459f23a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career resources'])[1]/following::span[4]</value>
      <webElementGuid>4b17bb2c-4fb4-46ef-a462-ca64e149b18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download apps'])[1]/preceding::span[1]</value>
      <webElementGuid>adde85b5-6edb-4b19-a2e2-d10d08e1b103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JobStreet @ App Store'])[1]/preceding::span[4]</value>
      <webElementGuid>c689f5d7-72c9-4985-9f18-e1200d762d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testimonials']/parent::*</value>
      <webElementGuid>8d301978-ad44-4ff4-94c5-bbb28801247a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/div/span/span</value>
      <webElementGuid>4bc3570b-1f48-418d-aec5-104e106f0288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Testimonials' or . = 'Testimonials')]</value>
      <webElementGuid>bf40e751-a51c-47bd-b88b-218b8bc07e3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
