<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-Singapore</name>
   <tag></tag>
   <elementGuidId>a5a3ee6a-bdca-40a7-8a9f-2ad8e2601611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation='country-switcher-menu']//a[@data-automation='Country - Singapore']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sx2jih0.sx2jihf.sx2jih0._1aq6jw0._18qlyvc22.zcydq89i.zcydq88i.zcydq84u.zcydq8p.zcydq8h.zcydq8fy.zcydq85._18qlyvc14._18qlyvc17.zcydq826.zcydq82h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>620ebf18-2cbc-478d-b6d3-9e17a9fd6519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>bb04108e-aa71-4dd0-96ce-717ed963afa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>32e220a1-7d20-45ee-b13e-8663fc2fde78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>Country - Singapore</value>
      <webElementGuid>4787fad0-cfee-439e-b5fb-3d32cea9a9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jihf sx2jih0 _1aq6jw0 _18qlyvc22 zcydq89i zcydq88i zcydq84u zcydq8p zcydq8h zcydq8fy zcydq85 _18qlyvc14 _18qlyvc17 zcydq826 zcydq82h</value>
      <webElementGuid>467312ee-f5d6-4d12-a293-cefb9178a32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://myjobstreet.jobstreet.com.sg/</value>
      <webElementGuid>3fa2cd9f-e4a1-4584-93d6-1093fea1e387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Singapore</value>
      <webElementGuid>74dce01d-2481-4479-b91b-922b0fd39715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation='country-switcher-menu']//a[@data-automation='Country - Singapore']</value>
      <webElementGuid>d3fd0b9b-f0cb-4b58-ba9e-afbc20449599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[5]/div/div/div[2]/div/div/div/div/div[2]/div/a[7]</value>
      <webElementGuid>57c0830d-3cb4-4153-91c0-5d8e0cc14151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Philippines'])[2]/following::a[1]</value>
      <webElementGuid>d5d1e52a-0b4b-483f-acbf-edef3383993d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Zealand'])[2]/following::a[2]</value>
      <webElementGuid>cf2fc85c-b37b-4fdb-a94a-ebee250a1c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thailand'])[2]/preceding::a[1]</value>
      <webElementGuid>89cc1a10-e0cb-4e85-af22-7b15b4cfa703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://myjobstreet.jobstreet.com.sg/')])[2]</value>
      <webElementGuid>567a4b17-b4f4-4385-9f8a-a4d1922dd6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[7]</value>
      <webElementGuid>cc8129d1-ca4f-40b0-af96-dd895a80bdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://myjobstreet.jobstreet.com.sg/' and (text() = 'Singapore' or . = 'Singapore')]</value>
      <webElementGuid>ff7569b7-80c1-4c18-ab46-710a38ebae2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
