<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text-recent-search-2</name>
   <tag></tag>
   <elementGuidId>f9dfd25a-4710-4091-b820-8b262b1a5e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation='recent-search-item-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f33908c-a40a-4ed9-9524-35fefb847352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 l3gun70 l3gun73 l3gun71</value>
      <webElementGuid>24198f6c-fdb7-4209-9cbc-259276d575b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>jobstreet.com</value>
      <webElementGuid>04965c8e-d955-483d-926a-486c2f3bc971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jobstreet.com</value>
      <webElementGuid>444a70bd-cb96-466a-a520-1266b24ef227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation='recent-search-item-1']</value>
      <webElementGuid>5eaf18a5-84cf-4fbd-b499-bfc5587ae1e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div[2]/div/div/div/div[2]/div[2]/a/div/div/div/span[2]/div</value>
      <webElementGuid>7555b0ef-9c1e-4fed-be24-3651d8e1892d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All locations'])[1]/following::div[6]</value>
      <webElementGuid>bdbb53c0-9c70-40e7-9200-866f2bf24362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qa automation'])[1]/following::div[9]</value>
      <webElementGuid>35fe55f2-2130-4725-b6df-7cefe4a84af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All locations'])[2]/preceding::div[1]</value>
      <webElementGuid>5bdc38a8-5227-44ba-be05-87db11a55041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All jobs'])[1]/preceding::div[5]</value>
      <webElementGuid>55a3dbd6-1a13-4f0f-95f4-d93fed7360a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jobstreet.com']/parent::*</value>
      <webElementGuid>ce5361df-a66b-4c97-afc3-12697d5b0845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/div/span[2]/div</value>
      <webElementGuid>f783f209-0a80-4998-8e3c-2f65af0bb246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'jobstreet.com' and (text() = 'jobstreet.com' or . = 'jobstreet.com')]</value>
      <webElementGuid>ec5b3d90-4c2f-4c97-9a84-967b9c9923d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
