<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-Job alerts</name>
   <tag></tag>
   <elementGuidId>8a516875-4445-4d94-ab3b-7123add82c51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-automation='profile-bar-job-alert-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69fcea03-f5f2-47c7-b92a-1e6d3acd4de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>303b7eb5-7394-4b27-a13a-62256fcf7f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>profile-bar-job-alert-btn</value>
      <webElementGuid>417b5e89-3456-4232-86ba-6bd0b9b43755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1hr6tkx5 _1hr6tkx6 sx2jih0 sx2jihf zcydq8h</value>
      <webElementGuid>0c44cfbd-44cc-453d-9d3b-86fc4dfbe3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>2c567f53-e172-41ec-a089-89fb4f0c0a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://myjobstreet.jobstreet.com.sg/my-job/job-alert.php</value>
      <webElementGuid>7653abf3-5b01-477b-a47d-d454cadc24f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job alerts</value>
      <webElementGuid>16a8ca9d-16f3-4bde-bad0-7a1992e5e697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@data-automation='profile-bar-job-alert-btn']</value>
      <webElementGuid>32286de6-863c-44ff-a6d3-282c489d7566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div/div/div[3]/span/a</value>
      <webElementGuid>4caced60-404f-4048-a584-df6579f5f5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Job alerts')]</value>
      <webElementGuid>cdce1cd0-338b-4821-bd3e-3e8c5402d30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job applications'])[3]/following::a[1]</value>
      <webElementGuid>47588492-4585-4884-b249-2e6a8bfcbd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved jobs'])[1]/following::a[2]</value>
      <webElementGuid>b52ffa60-1665-424f-89ab-a7938e8ad75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved jobs'])[2]/preceding::a[1]</value>
      <webElementGuid>94e0b421-5270-4798-a45e-185ca31e7b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job applications'])[4]/preceding::a[1]</value>
      <webElementGuid>7be2f959-8fd8-4161-80cb-93ae505c813a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Job alerts']/parent::*</value>
      <webElementGuid>a8194cac-0034-47a8-85df-d2c7d96271f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://myjobstreet.jobstreet.com.sg/my-job/job-alert.php')]</value>
      <webElementGuid>e9206cd2-41e3-4923-8363-48229626bf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/a</value>
      <webElementGuid>a72da531-94fc-4b53-b7c8-b4f389fcef86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://myjobstreet.jobstreet.com.sg/my-job/job-alert.php' and (text() = 'Job alerts' or . = 'Job alerts')]</value>
      <webElementGuid>cdcc9bb2-c359-4dde-a5a7-50330feb686f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
