<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-Saved jobs</name>
   <tag></tag>
   <elementGuidId>89c32cd1-dade-4349-8aef-43a1522c02a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-automation='profile-bar-save-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a._1hr6tkx5._1hr6tkx6.sx2jih0.sx2jihf.zcydq8h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4984914c-f69c-4214-91a6-260563b1af4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>ad10a813-cd57-4306-8445-2c3a2c339e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>profile-bar-save-btn</value>
      <webElementGuid>9dfc0885-f8ed-4c1f-8068-55c2f8eb6a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1hr6tkx5 _1hr6tkx6 sx2jih0 sx2jihf zcydq8h</value>
      <webElementGuid>ece5ed4e-24f8-4245-aa2e-0727cb55e7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>33b13f7b-da03-4532-9024-08d2aa6557b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#savedJobs</value>
      <webElementGuid>39a0f025-8d96-476c-b938-659ce444db79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saved jobs</value>
      <webElementGuid>fb8b5cd8-4706-4036-9d04-c7f68c1ee1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@data-automation='profile-bar-save-btn']</value>
      <webElementGuid>ff3db745-63c4-4b8e-959e-c5510f52a6f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div/div/div/span/a</value>
      <webElementGuid>fd25fc2e-d66d-44b9-b011-7c26868715b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Saved jobs')]</value>
      <webElementGuid>91f0b05c-93ff-43fa-8d17-61845d777cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View profile'])[3]/following::a[1]</value>
      <webElementGuid>4bde6304-e17e-4114-a4d5-dd5015788efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job applications'])[3]/preceding::a[1]</value>
      <webElementGuid>9076e87d-df0d-4359-a66f-7e673c957d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job alerts'])[1]/preceding::a[2]</value>
      <webElementGuid>c0d889f6-eac1-4ace-9c70-37d08dc5e34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saved jobs']/parent::*</value>
      <webElementGuid>9f8c02c2-6846-41d6-a859-d91cc8a63afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#savedJobs')]</value>
      <webElementGuid>05984871-8b09-4d4f-a0cf-a0b6e1c7d992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span/a</value>
      <webElementGuid>3466be5f-2c3a-4592-a1ce-78ebb37d97bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#savedJobs' and (text() = 'Saved jobs' or . = 'Saved jobs')]</value>
      <webElementGuid>aaf92636-7bb8-4859-95a5-22cbaf54cba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
