<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error-login</name>
   <tag></tag>
   <elementGuidId>a6533de2-34be-4c9a-b2cd-8168f9754cfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#err_login_failed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='err_login_failed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>30f28094-6be1-42f7-b77c-a72e57ac0b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>err_login_failed</value>
      <webElementGuid>91e3e6c6-fd17-4df5-8738-3928cf03d21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We're sorry, either the Email or Password was incorrect. Please try again.If you have forgotten your Email or Password, retrieve it here.</value>
      <webElementGuid>46a4e112-c96f-4529-93c2-068e4cf1814a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[@id='err_login_failed']</value>
      <webElementGuid>16c597e2-2305-4f96-a7de-7128c7f8cb45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='err_login_failed']</value>
      <webElementGuid>1fa93ffa-8916-41d1-999e-72eba129c19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_error']/p</value>
      <webElementGuid>55147e12-ccae-4f91-a38d-47229b593c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::p[1]</value>
      <webElementGuid>874cc9f1-613b-4b62-b8f1-cab3e711949d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('It', &quot;'&quot;, 's fast and easy. We', &quot;'&quot;, 'll never post anything without your permission')])[1]/following::p[1]</value>
      <webElementGuid>2028b97f-bd9a-4c77-92ce-4000602e04fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/preceding::p[1]</value>
      <webElementGuid>875291c2-22f0-4b83-ba0e-8c9541bc55fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/p</value>
      <webElementGuid>fb5673c5-67c8-4d14-bdf5-0fe2e0e556d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'err_login_failed' and (text() = concat(&quot;We&quot; , &quot;'&quot; , &quot;re sorry, either the Email or Password was incorrect. Please try again.If you have forgotten your Email or Password, retrieve it here.&quot;) or . = concat(&quot;We&quot; , &quot;'&quot; , &quot;re sorry, either the Email or Password was incorrect. Please try again.If you have forgotten your Email or Password, retrieve it here.&quot;))]</value>
      <webElementGuid>04254f1a-30b8-4740-90d1-579f51fdb1d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
