<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-Sign up</name>
   <tag></tag>
   <elementGuidId>0587b4d7-fe52-40d4-8cc5-99a383992312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_signup_now</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_signup_now']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2144cd5b-f9c3-4039-a72b-ab4746acc17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_signup_now</value>
      <webElementGuid>25739329-4b3a-47be-ac71-10225f814c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://myjobstreet.jobstreet.com.my/registration/simple-signup.php?site=my&amp;language_code=3</value>
      <webElementGuid>b7e5b55f-6e3c-4fcc-8749-c806d44b6c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up FREE Now</value>
      <webElementGuid>f753a7d5-2210-4353-942a-72bba5309c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='btn_signup_now']</value>
      <webElementGuid>d0eb8bcd-0a91-47fc-b814-85c7911a1760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_signup_now']</value>
      <webElementGuid>eaa24c2a-2f27-4758-9caf-c2b6792e9179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='lbl_new']/a</value>
      <webElementGuid>cc5507d7-0c2e-44d0-8187-8984e8d12a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign up FREE Now')]</value>
      <webElementGuid>263a2439-c622-47c4-a982-3ed2cac0eaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/following::a[1]</value>
      <webElementGuid>d8f35f6b-8613-4c7f-a2a5-a4b1eaa09988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Use'])[1]/preceding::a[1]</value>
      <webElementGuid>b6319a6d-4af6-44bf-ac60-137f8282e479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up FREE Now']/parent::*</value>
      <webElementGuid>d37a1188-121d-489b-9231-73b2c4a9c35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://myjobstreet.jobstreet.com.my/registration/simple-signup.php?site=my&amp;language_code=3')]</value>
      <webElementGuid>cd9c2029-375b-4359-8d3f-480c932f62b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/a</value>
      <webElementGuid>91158c71-cbe6-4363-b65a-732412a9284e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_signup_now' and @href = 'https://myjobstreet.jobstreet.com.my/registration/simple-signup.php?site=my&amp;language_code=3' and (text() = 'Sign up FREE Now' or . = 'Sign up FREE Now')]</value>
      <webElementGuid>30dce148-5220-41b9-85fb-3aeaf5a036ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
