<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-Forgot-password</name>
   <tag></tag>
   <elementGuidId>5a442ef5-de4d-411f-97f5-f8904db51643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#span_forgot_password > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='span_forgot_password']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b3e3cb9b-8bf6-4d42-8805-37ce7650b710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://myjobstreet.jobstreet.com.my/home/forgot-password.php?site=my&amp;language_code=3</value>
      <webElementGuid>16f16516-b9a0-4e0c-802c-c6086fc68b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot?</value>
      <webElementGuid>8db38445-a7bd-4f2a-86fc-4e955adbd17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='span_forgot_password']/a</value>
      <webElementGuid>55e535b9-b7e2-423f-aae7-e46b01ee6376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='span_forgot_password']/a</value>
      <webElementGuid>2c57f3d4-137e-4487-8b35-bde779d3abc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot?')]</value>
      <webElementGuid>ee00b553-b8c0-4548-97bc-14b10d57d628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::a[1]</value>
      <webElementGuid>eb8027d3-0653-4456-af3f-5aecb00de3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::a[1]</value>
      <webElementGuid>e8d63bbf-94f2-493b-80af-0528c9e200fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/preceding::a[1]</value>
      <webElementGuid>5a1036a3-9908-4232-a892-41f7ce75e9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot?']/parent::*</value>
      <webElementGuid>a17e0aea-3c6a-4ed4-8960-da833f7cd213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://myjobstreet.jobstreet.com.my/home/forgot-password.php?site=my&amp;language_code=3')]</value>
      <webElementGuid>2192b69c-9f13-4c44-b6c9-fe5c3b9441c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>86b17d5d-f648-48d5-a72a-852863d6167f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://myjobstreet.jobstreet.com.my/home/forgot-password.php?site=my&amp;language_code=3' and (text() = 'Forgot?' or . = 'Forgot?')]</value>
      <webElementGuid>c3ce9f68-943a-4692-90e4-6ce401f096e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
