<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ckbox-Last 7 days</name>
   <tag></tag>
   <elementGuidId>2f278c45-5e47-417a-a127-af29ea9ab9e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation='filterDropdown-CREATED_AT']//span[text()='Last 7 days']/parent::div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>404a7ef4-2a04-4d67-bcdb-512ffd900f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq86i zcydq87i zcydq89m zcydq88m zcydq856 zcydq8eu zcydq8h HVVuU_0</value>
      <webElementGuid>dbcd3098-f1a7-4737-9743-e18b490c3ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>SingleCheckboxGroup</value>
      <webElementGuid>9f6f9fec-eac5-4961-8df9-d5f3a28a0221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>createdAt</value>
      <webElementGuid>a22415ed-cfdd-4e19-afa5-1c4579bb68d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last 7 days</value>
      <webElementGuid>5edc44aa-6c35-409e-a738-eae913f60958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation='filterDropdown-CREATED_AT']//span[text()='Last 7 days']/parent::div</value>
      <webElementGuid>35d6ab9f-f6d2-4af3-aaee-a580b2a6edf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@name='createdAt'])[4]</value>
      <webElementGuid>dab50b9d-6794-46bf-ac38-a0ac41f3a7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='srpSearchForm']/div/div/form/div/div[2]/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div/div/div/div/div[4]/div</value>
      <webElementGuid>bc30f223-353f-46c6-817f-bd2fb4e0991f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last 3 days'])[1]/following::div[2]</value>
      <webElementGuid>339333c2-4ebd-4834-a7ed-40311afb8378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last 24 hours'])[1]/following::div[4]</value>
      <webElementGuid>b051d82a-7da4-4e98-9863-7bf3c114ab79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last 14 days'])[1]/preceding::div[1]</value>
      <webElementGuid>f6a45752-00f0-45b8-ae51-7f9d7dad9fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>5d00ea5c-dc34-4481-b6ea-abfb835f7fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'createdAt' and (text() = 'Last 7 days' or . = 'Last 7 days')]</value>
      <webElementGuid>3d54103e-5e76-4d2e-8f4e-79493cfff856</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
