<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ckbox-Any Time</name>
   <tag></tag>
   <elementGuidId>83ebb54e-bd15-4dda-bce9-07848766b8f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation='filterDropdown-CREATED_AT']//span[text()='Any Time']/parent::div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;createdAt&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>803c65c3-f14a-4834-a2ab-837dd2edcae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq86i zcydq87i zcydq89m zcydq88m zcydq856 zcydq8eu zcydq8h HVVuU_0</value>
      <webElementGuid>16db5b7e-a2b5-4b64-bd33-39f937c6d3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>SingleCheckboxGroup</value>
      <webElementGuid>241471d7-e3f4-4494-9da4-cc820f639b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>createdAt</value>
      <webElementGuid>7dab33f0-ff10-45dd-8fcd-3868b31d8223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Any Time</value>
      <webElementGuid>2e82bfd1-4e1a-4fe5-b89d-13b2904f420e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation='filterDropdown-CREATED_AT']//span[text()='Any Time']/parent::div</value>
      <webElementGuid>e2c96260-029a-479d-8c9c-5efd150b69bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='createdAt']</value>
      <webElementGuid>a4e26cbe-2fb5-49a4-9d5d-e62a7167b378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='srpSearchForm']/div/div/form/div/div[2]/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div/div/div/div/div/div</value>
      <webElementGuid>4b58a33a-5faf-4d2d-a1ad-f06a73a0dc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date posted'])[2]/following::div[8]</value>
      <webElementGuid>be0c3eaf-b909-41a2-a47c-583bfda7f7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job type'])[2]/following::div[11]</value>
      <webElementGuid>4621ce5b-95c5-49a9-8ce6-f769a4e7e9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last 24 hours'])[1]/preceding::div[1]</value>
      <webElementGuid>1f0b2e7f-57cc-4fe7-af24-11848bc4de77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[3]/div/div/div/div/div/div</value>
      <webElementGuid>e1779165-1cfa-4373-ad08-13d7d44f73d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'createdAt' and (text() = 'Any Time' or . = 'Any Time')]</value>
      <webElementGuid>582973a8-e200-41cd-9b7d-447a2b2b4c37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
