<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-next</name>
   <tag></tag>
   <elementGuidId>d3eb32ef-664e-4a25-a186-2ff3fa6be630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.sx2jih0.zcydq896.zcydq886.zcydq8o.zcydq856.zcydq8ea.zcydq8h.zcydq8y.zcydq8x.IQYn5_0._18qlyvc14._18qlyvc17.zcydq832.zcydq835</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@data-automation='pagination']/a)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c62ff3a-6a0e-4ed3-92e3-1d09c2c2de06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job-search/qa-automation-jobs/2/</value>
      <webElementGuid>d6f34d08-3eb1-452e-ae3a-0d3fa08ac8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>4af5b5fe-028a-4d1c-a695-3cd0c4708f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq896 zcydq886 zcydq8o zcydq856 zcydq8ea zcydq8h zcydq8y zcydq8x IQYn5_0 _18qlyvc14 _18qlyvc17 zcydq832 zcydq835</value>
      <webElementGuid>00006add-510d-45fd-816e-7c4fcab35e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>37503b12-51ee-44d6-b5a8-f21658a57820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-automation='pagination']/a)[2]</value>
      <webElementGuid>10eab18e-21e4-4139-9978-21c2795edeff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobList']/div[2]/div[3]/div/a</value>
      <webElementGuid>e1f92a98-6520-4866-a29f-67acd8fd2eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/following::a[1]</value>
      <webElementGuid>ba766643-cc7c-4646-b1ef-3ecc58a2a805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full-Time'])[25]/following::a[1]</value>
      <webElementGuid>5d63d993-c240-4c3c-8cd9-04b9fb097d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Now'])[1]/preceding::a[1]</value>
      <webElementGuid>ddde073e-dce7-4a4d-9c94-f8e45988129d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/job-search/qa-automation-jobs/2/')]</value>
      <webElementGuid>30d7dcb7-aa24-4032-96b3-c5d7c600f6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>cbe82fa8-eaa9-467a-ae40-2af95f9d837e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job-search/qa-automation-jobs/2/' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>8dc23c4f-523d-4a90-8254-8f1a5c71349b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
