<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-prev</name>
   <tag></tag>
   <elementGuidId>774d62cc-8ded-4c60-96b6-d6205475f12a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.sx2jih0.zcydq896.zcydq886.zcydq8o.zcydq856.zcydq8ea.zcydq8h.zcydq8y.zcydq8x.IQYn5_0._18qlyvc14._18qlyvc17.zcydq832.zcydq835</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@data-automation='pagination']/a)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dccd3a05-11e4-4797-b4ba-2353fef69f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job-search/qa-automation-jobs/1/</value>
      <webElementGuid>57f60857-ddfd-4182-bf24-c7b201f5f4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq896 zcydq886 zcydq8o zcydq856 zcydq8ea zcydq8h zcydq8y zcydq8x IQYn5_0 _18qlyvc14 _18qlyvc17 zcydq832 zcydq835</value>
      <webElementGuid>43ca6bc2-6895-4c0d-a452-408d3f558a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prev</value>
      <webElementGuid>547d86c9-847c-4005-a21d-065966b45210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@data-automation='pagination']/a)[1]</value>
      <webElementGuid>273dc0e4-2744-46d2-9a23-42f8ab37acb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobList']/div[2]/div[3]/div/a</value>
      <webElementGuid>3fb8c8b7-8d12-4879-9e3a-44b6c4cd6747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full-Time'])[28]/following::a[1]</value>
      <webElementGuid>f56c50f6-418b-4843-8f83-91dd60a78bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Type'])[30]/following::a[2]</value>
      <webElementGuid>4e607d4a-b780-43b9-816a-9af7aea3581b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::a[1]</value>
      <webElementGuid>ae655406-1f11-43ea-975b-cdee133be54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/job-search/qa-automation-jobs/1/')]</value>
      <webElementGuid>44d54ab0-c3b0-4f22-8dda-ecc7cf1834c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>a7c15431-3ce8-42ff-900c-b5b144676f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job-search/qa-automation-jobs/1/' and (text() = 'Prev' or . = 'Prev')]</value>
      <webElementGuid>17cbf856-ba04-4ea3-a39a-8af5b4801078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
