<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown-pagination</name>
   <tag></tag>
   <elementGuidId>06235733-6e83-4d05-9a14-f4b83bde15e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pagination</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation='pagination-dropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9f54d979-7611-44e5-af49-a7d91dafd07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih1 sx2jih6 sx2jih7 sx2jiha zcydq8p zcydq89i zcydq85u zcydq85 tfxl6i0 _3dxvbx0 _3dxvbx1 _18qlyvc0 _18qlyvc1x _18qlyvc1 _18qlyvca _18qlyvc22 _18qlyvc14  zcydq832</value>
      <webElementGuid>9e2baa36-1b8f-418e-bd3d-6438fde12436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pagination</value>
      <webElementGuid>d7ea0239-d653-460a-a8ab-f304c2a0028e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Pagination dropdown</value>
      <webElementGuid>feae0952-0160-4337-8929-3ea97573f1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>123456789101112...21</value>
      <webElementGuid>098d5888-2ce5-4a85-94bc-cb84732119f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation='pagination-dropdown']</value>
      <webElementGuid>81715971-ca04-4db6-98c8-ff38af022a0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pagination']</value>
      <webElementGuid>aa82cdce-598a-4369-9b63-21af7983df79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobList']/div[2]/div[3]/div/div/div/div/div/select</value>
      <webElementGuid>796e5445-8aa9-4b2b-88bb-5c6e813a64aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/following::select[1]</value>
      <webElementGuid>863aac23-4bf0-4a2f-8d99-3cd748e536cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full-Time'])[28]/following::select[1]</value>
      <webElementGuid>0b71ff47-868c-4c11-8a46-5502592670dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::select[1]</value>
      <webElementGuid>7a569c8a-520d-475f-9b97-1a31d54d6746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Now'])[1]/preceding::select[1]</value>
      <webElementGuid>a7ba5959-7b5f-4100-8e8f-cb9914dd0a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/select</value>
      <webElementGuid>1d77dcee-062f-4f2b-88f8-beb4bb4ac5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pagination' and (text() = '123456789101112...21' or . = '123456789101112...21')]</value>
      <webElementGuid>a064e294-baaf-4734-a959-b864971d51b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
