<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>links-related-searches</name>
   <tag></tag>
   <elementGuidId>ef64d8ee-5fe6-414d-95f2-9c4ccea2f0f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.sx2jih0._18qlyvc0._18qlyvch._1d0g9qk4._18qlyvcs._18qlyvc1x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@data-automation='related_search_heading']/ancestor::div[2]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>1f082272-9b16-46f2-9b11-2e06d2cc84b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 _18qlyvc0 _18qlyvch _1d0g9qk4 _18qlyvcs _18qlyvc1x</value>
      <webElementGuid>4b1abb3c-fd14-4e03-b592-9578097af869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>related_search_heading</value>
      <webElementGuid>a7ac2ea3-5609-4f87-99a4-b6c6e6bd9c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>83bd6de9-6d84-40ba-a5b3-2cb382be91fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Searches related to qa automation jobs</value>
      <webElementGuid>7fbc4bce-5144-4cb6-9307-d38a10c103e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h4[@data-automation='related_search_heading']/ancestor::div[2]//a</value>
      <webElementGuid>bc91ef08-1324-42bd-8db1-dfbbaa0ea7ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobList']/div/div/div/div/h4</value>
      <webElementGuid>6f291780-9ea5-41da-8e38-52ba8427e216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[1]/following::h4[1]</value>
      <webElementGuid>60129992-a8b1-4b8e-addf-3a287844e7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/following::h4[1]</value>
      <webElementGuid>b3f2c6c4-d24c-4792-b7fb-dd571767c426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qa engineer jobs'])[1]/preceding::h4[1]</value>
      <webElementGuid>836d78e3-5739-407b-9d1a-ab0beda5caa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='selenium jobs'])[1]/preceding::h4[1]</value>
      <webElementGuid>e44eae0e-35e4-40fd-8037-07ccdd66c57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Searches related to qa automation jobs']/parent::*</value>
      <webElementGuid>b2dfb0d4-a3e1-4538-b865-ba909faea4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>b4e958ac-b64b-4947-b383-c423fd290360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Searches related to qa automation jobs' or . = 'Searches related to qa automation jobs')]</value>
      <webElementGuid>b7321403-3f25-4c72-b6ff-18273e549915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
