<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Close</name>
   <tag></tag>
   <elementGuidId>87d87878-c023-488b-9734-16b44f43fa58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-automation='jobTeaserLinkBtnClose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.sx2jih0.zcydq84u._18qlyvc0._18qlyvc1z._1hr6tkx7._18qlyvc2._1d0g9qk4._18qlyvcb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b58de72-743b-4033-804f-3afe5c513a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq84u _18qlyvc0 _18qlyvc1z _1hr6tkx7 _18qlyvc2 _1d0g9qk4 _18qlyvcb</value>
      <webElementGuid>ccf963d1-81d8-4df3-be78-bb702007b8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>3265ffb9-79d1-4d04-ba79-4f7f4a92ffc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-automation='jobTeaserLinkBtnClose']</value>
      <webElementGuid>ed4c0e8a-76cd-4c5f-bb9a-55eb1306525c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div[2]/div/div/div/div[2]/div/div/div/div/div/button/span</value>
      <webElementGuid>fcd1c9b5-fee1-4da8-85e4-6cce631ccdd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View in new tab'])[1]/following::span[1]</value>
      <webElementGuid>f92e2fee-78a0-48dd-8569-d18ef2a87005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Now'])[1]/following::span[2]</value>
      <webElementGuid>a7f863cc-b73a-430a-8146-413be3f20d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation QA Engineer And Tester (Staytion)'])[2]/preceding::span[1]</value>
      <webElementGuid>e1705a39-3a3b-4a3b-99e5-5eba1cea8bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stellar Lifestyle Pte. Ltd.'])[2]/preceding::span[1]</value>
      <webElementGuid>7ebe288a-047a-4d55-8cdd-140fa924263a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>ff6601cd-0c95-4151-9fc9-2cc79783bb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button/span</value>
      <webElementGuid>41561ddd-d02a-4f6b-a5e0-d4c322312acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>ec52b28e-5ca1-4ee3-a4b4-07d834827fdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
