<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img-company-logo</name>
   <tag></tag>
   <elementGuidId>8ec32577-1593-4164-8e56-076bb8520e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation='job-card-logo']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>47772915-8bbd-4763-b0e4-491c0a380f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 pXyoU_0</value>
      <webElementGuid>d09af445-629a-484d-a968-27c1cc64072b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image-service-cdn.seek.com.au/08c592f3212b34b4141360b815b8ce78b6285147/ee4dce1061f3f616224767ad58cb2fc751b8d2dc</value>
      <webElementGuid>76c6bf17-c310-4e9f-9e9b-606aefbbb60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Smartidea Pte Ltd's logo</value>
      <webElementGuid>32c7a9d1-6cc2-4cd8-9639-f63ae442f89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation='job-card-logo']/img</value>
      <webElementGuid>189d507e-2ca8-46d8-9f07-6c4e7e76a745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobList']/div[2]/div[2]/div/div[10]/div/div/article/div/div/div/div/div[2]/img</value>
      <webElementGuid>24391d25-14fa-4097-8111-fdd420a18eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;Smartidea Pte Ltd's logo&quot;]</value>
      <webElementGuid>63db33d6-edd3-4324-87a3-991ecca691c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/article/div/div/div/div/div[2]/img</value>
      <webElementGuid>af3682dd-ee5d-4774-82cc-a9a5909780d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://image-service-cdn.seek.com.au/08c592f3212b34b4141360b815b8ce78b6285147/ee4dce1061f3f616224767ad58cb2fc751b8d2dc' and @alt = concat(&quot;Smartidea Pte Ltd&quot; , &quot;'&quot; , &quot;s logo&quot;)]</value>
      <webElementGuid>dfe50173-696e-4417-8246-55145b7e544d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
