<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text-location</name>
   <tag></tag>
   <elementGuidId>75e22100-7553-4af6-9afb-7b67d5f58cfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation='job-card-logo']/following-sibling::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-automation='job-card-logo']/following-sibling::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dba3db76-1061-42aa-952e-665bf3fb0a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job-search/qa-automation-jobs-in-orchard/</value>
      <webElementGuid>9036436c-d91d-45b5-a52d-415e7d3a6f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>jobCardLocationLink</value>
      <webElementGuid>11d09378-be6a-45e3-8c98-663f156e2dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Limit results to Orchard in Central</value>
      <webElementGuid>3cb47e27-4b89-4693-a1cc-02cfe4e940b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jihf QytTO</value>
      <webElementGuid>d3042442-b202-40d8-be3a-9c0ecc9c8182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orchard</value>
      <webElementGuid>8a92166b-8a35-4db4-8052-d5910c383ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation='job-card-logo']/following-sibling::span[1]</value>
      <webElementGuid>1213067b-c51a-4b75-8c12-617bb6ca0409</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobList']/div[2]/div[2]/div/div[10]/div/div/article/div/div/div/div/span/span/a</value>
      <webElementGuid>c91cd7aa-5fae-4766-97fa-b8c9cbc518d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Orchard')]</value>
      <webElementGuid>89a09952-1461-441a-8122-60dcae486718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smartidea Pte Ltd'])[1]/following::a[1]</value>
      <webElementGuid>ff8c9fb1-1962-4bb7-baf9-109e5b9a8cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software QA Engineer'])[1]/following::a[2]</value>
      <webElementGuid>0a061575-c053-4d0e-b641-0cb4288506aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGD 4.3K - 6K monthly'])[1]/preceding::a[1]</value>
      <webElementGuid>729d2aef-be09-4432-ac39-48daa376e0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work-life balance'])[1]/preceding::a[1]</value>
      <webElementGuid>1691f90e-08ef-474f-8bfe-74a47e3eebae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Orchard']/parent::*</value>
      <webElementGuid>ea9d8cc4-6d7e-4a68-bcf3-99066f64bb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/job-search/qa-automation-jobs-in-orchard/')]</value>
      <webElementGuid>a13e9554-31e3-44a3-b969-f3ab7b24c476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/article/div/div/div/div/span/span/a</value>
      <webElementGuid>7452f1bc-a540-4b81-baa7-562975fa76b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job-search/qa-automation-jobs-in-orchard/' and @title = 'Limit results to Orchard in Central' and (text() = 'Orchard' or . = 'Orchard')]</value>
      <webElementGuid>4b9c9b09-b409-41bc-b831-4367f2b379a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
