<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text-company-name</name>
   <tag></tag>
   <elementGuidId>29947121-e2dc-4a73-acb0-82eee4cee372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[contains(@data-automation, 'job-card')]//h1/following-sibling::span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//article[contains(@data-automation, 'job-card')]//h1/following-sibling::span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d80201e-c1e7-4b85-b8a2-d5545f8fce7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job-search/jobs-at-stellar-lifestyle-pte.-ltd./</value>
      <webElementGuid>507877ac-63a2-40f7-b8ba-631eb79da5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>1fa72c8f-bb48-4ac3-9e21-2d60a5194176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>jobCardCompanyLink</value>
      <webElementGuid>0d775e32-6239-4c24-8c03-2dff7e90cd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show more jobs at Stellar Lifestyle Pte. Ltd.</value>
      <webElementGuid>1ead564d-7257-4f0d-b323-e2ade649ef9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jihf QytTO</value>
      <webElementGuid>242942e4-a642-4489-a1d1-de800717e47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stellar Lifestyle Pte. Ltd.</value>
      <webElementGuid>6927d0b3-75e4-4f7a-9520-a09b16135e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//article[contains(@data-automation, 'job-card')]//h1/following-sibling::span</value>
      <webElementGuid>db1bccf1-6e6e-402e-973d-3f62f0170723</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobList']/div[2]/div[2]/div/div[2]/div/div/article/div/div/div/div/div[3]/span/span/a</value>
      <webElementGuid>e2e6a2f8-13a6-43bc-a308-c0985834af26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Stellar Lifestyle Pte. Ltd.')]</value>
      <webElementGuid>92f2b208-a946-4338-9284-f21175e9ce27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automation QA Engineer And Tester (Staytion)'])[1]/following::a[1]</value>
      <webElementGuid>a01952d7-a077-4823-bdc7-66ac7620489b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full-Time'])[1]/following::a[2]</value>
      <webElementGuid>d870dd9e-68c7-46e1-ac59-ab81419e5e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[4]/preceding::a[1]</value>
      <webElementGuid>cd0a1597-43ed-4f03-856a-c0e32649cb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stellar Lifestyle Pte. Ltd.']/parent::*</value>
      <webElementGuid>190a81ae-c860-4b2f-8293-5639323c87ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/job-search/jobs-at-stellar-lifestyle-pte.-ltd./')]</value>
      <webElementGuid>8fbba544-7d45-41a3-ad94-3be129120229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/article/div/div/div/div/div[3]/span/span/a</value>
      <webElementGuid>d5b65f80-4c86-4f94-9865-e828132195ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job-search/jobs-at-stellar-lifestyle-pte.-ltd./' and @title = 'Show more jobs at Stellar Lifestyle Pte. Ltd.' and (text() = 'Stellar Lifestyle Pte. Ltd.' or . = 'Stellar Lifestyle Pte. Ltd.')]</value>
      <webElementGuid>2c4eedb5-fede-433a-b986-79750cfbaa76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
