<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text-job-type</name>
   <tag></tag>
   <elementGuidId>80afc735-5e13-485d-9960-a3942c789eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-automation='jobCardJobTypeLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dc2c2126-e141-49ee-8388-1f084a21fa43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job-search/qa-automation-jobs/?job-type=full_time</value>
      <webElementGuid>c22267d3-6521-40a4-a49c-dda36bf07bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>92a4aaa8-50c6-47fd-847e-659c4b293c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>jobCardJobTypeLink</value>
      <webElementGuid>79a3d27d-9d7b-468f-9588-b680ba32ccc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Limit results to Full-Time </value>
      <webElementGuid>8cee01ce-62c2-4143-b94b-f50387570934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1hr6tkx5 _1hr6tkx8 _1hr6tkxb sx2jih0 sx2jihf zcydq8h</value>
      <webElementGuid>307b775a-b71b-4f53-9274-656c34a6603f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full-Time</value>
      <webElementGuid>e0d6c145-c4d2-4a78-9797-a31ecc410d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@data-automation='jobCardJobTypeLink']</value>
      <webElementGuid>bb6f2336-091f-462c-98aa-1734f0001269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobList']/div[2]/div[2]/div/div[3]/div/div/article/div/div/div[2]/div/div/dl/dd[3]/a</value>
      <webElementGuid>34d8a14c-8dd3-4e9f-9b7a-fe22f5202895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Full-Time')])[2]</value>
      <webElementGuid>b3bf0e4b-369e-493b-9d8b-ae13c81f8472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Type'])[3]/following::a[1]</value>
      <webElementGuid>88c4f634-7016-476f-afe8-033484e12ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT-Software'])[2]/following::a[1]</value>
      <webElementGuid>5a673beb-3b8f-40ac-b161-3ee8d3363db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Automation Architect'])[1]/preceding::a[1]</value>
      <webElementGuid>86fd671d-566e-48c5-a62e-dd8dcc32671b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jetstar Regional Services Pte Ltd'])[1]/preceding::a[2]</value>
      <webElementGuid>cda4e006-6d81-45ed-b372-2dadfc2bb18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/job-search/qa-automation-jobs/?job-type=full_time')])[2]</value>
      <webElementGuid>b04bf88d-9391-4d23-b53a-fd20b3976793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/article/div/div/div[2]/div/div/dl/dd[3]/a</value>
      <webElementGuid>f5f444f9-26a1-4587-9462-2e8cf4dae3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job-search/qa-automation-jobs/?job-type=full_time' and @title = 'Limit results to Full-Time ' and (text() = 'Full-Time' or . = 'Full-Time')]</value>
      <webElementGuid>d158cc84-a7e4-4649-88c9-d57309df9730</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
