<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text-selling-points</name>
   <tag></tag>
   <elementGuidId>7878acff-ba4f-4b49-ac0e-1ec1f8eaa487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation='job-card-selling-points']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>79036413-9a5e-4dcf-9715-0dc8af0f7d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq84u _18qlyvc0 _18qlyvc1x _18qlyvc1 _1d0g9qk4 _18qlyvc8</value>
      <webElementGuid>7881a7e9-19ac-40fd-ad51-930fe44652b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work-life balance</value>
      <webElementGuid>a7db71bc-7ed1-425c-a232-246edc9e98b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation='job-card-selling-points']</value>
      <webElementGuid>ee9777e3-6829-4d2b-aa86-74197b6731d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobList']/div[2]/div[2]/div/div[10]/div/div/article/div/div/div/div/div[4]/ul/li/div/div[2]/span</value>
      <webElementGuid>6eb1987d-cb14-4314-870c-be46f222c0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGD 4.3K - 6K monthly'])[1]/following::span[1]</value>
      <webElementGuid>d1900b23-a8ce-48d4-a42d-2ebc3ccd494a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orchard'])[1]/following::span[2]</value>
      <webElementGuid>c351cae3-bec0-4002-8309-9aa5941096e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In house and external training provided to upkeep latest IT skill'])[1]/preceding::span[1]</value>
      <webElementGuid>c91b25b2-dadf-4200-82ab-d090723c214e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friendly and warm working environment'])[1]/preceding::span[2]</value>
      <webElementGuid>e0a1b533-c601-4f96-9b75-275a6133d13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Work-life balance']/parent::*</value>
      <webElementGuid>09087516-6d5a-454a-948b-7889ee629e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/article/div/div/div/div/div[4]/ul/li/div/div[2]/span</value>
      <webElementGuid>97dcea35-e691-4141-9932-d1ebff09d93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Work-life balance' or . = 'Work-life balance')]</value>
      <webElementGuid>64da3c64-66f5-4be9-99eb-d36be5e93359</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
