<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text-job-specializations</name>
   <tag></tag>
   <elementGuidId>2f477cbb-67e9-4eca-8877-37dd4e7a4e87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-automation='jobCardCategoryLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>84b1cf68-8f34-4461-9518-d11096896382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job-search/qa-automation-jobs/?specialization=508</value>
      <webElementGuid>d5b1bf04-0073-4d03-a6da-2a63f57b4191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>3bc97df0-6fc4-4194-8ef4-f3175451eb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>jobCardCategoryLink</value>
      <webElementGuid>69e424a5-c48a-414b-9e93-7b148d634499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Limit results to Computer/Information Technology </value>
      <webElementGuid>8d37f8ab-3a32-463d-96c9-8ffbf47004e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1hr6tkx5 _1hr6tkx8 _1hr6tkxb sx2jih0 sx2jihf zcydq8h</value>
      <webElementGuid>57f3a1e4-b8cf-493f-8bfa-d588a1ed4bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>77966880-c1f3-46dc-906f-913d5e2acd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Computer/Information Technology</value>
      <webElementGuid>a82793fa-a33c-4737-9d39-3bee5328bd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@data-automation='jobCardCategoryLink']</value>
      <webElementGuid>3971bdba-019f-403f-894b-8bf9f61ff297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jobList']/div[2]/div[2]/div/div[3]/div/div/article/div/div/div[2]/div/div/dl/dd/a</value>
      <webElementGuid>4a76e6e5-3ac3-416a-90f4-afd59a535ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Computer/Information Technology')])[2]</value>
      <webElementGuid>23d5869c-f01c-4280-9079-e3795f44c287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Specializations'])[3]/following::a[1]</value>
      <webElementGuid>29766cc9-4149-43f9-a9a1-68d2bd65d72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT-Software'])[2]/preceding::a[1]</value>
      <webElementGuid>a89a09df-e42c-40e4-b9ba-e04cee9f4e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Type'])[3]/preceding::a[2]</value>
      <webElementGuid>5dcd055b-0be1-41cd-b8e3-d67bb016e2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/job-search/qa-automation-jobs/?specialization=508')])[2]</value>
      <webElementGuid>39b3c8bf-680c-4868-bf24-ee75c298e20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/article/div/div/div[2]/div/div/dl/dd/a</value>
      <webElementGuid>53549268-9fdb-42d0-8121-8a09d45b608c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job-search/qa-automation-jobs/?specialization=508' and @title = 'Limit results to Computer/Information Technology ' and (text() = 'Computer/Information Technology' or . = 'Computer/Information Technology')]</value>
      <webElementGuid>908762e8-179a-45b2-8f1a-dda2c9f6d43b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
