<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-FAQ</name>
   <tag></tag>
   <elementGuidId>ff596b31-f006-471e-8375-6fb239afc693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-automation='FAQ']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d01eafec-29d1-4073-bbb9-2e483cc9ef9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 rxszx01</value>
      <webElementGuid>53fb2a3b-094c-4adf-967f-47609a499303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FAQ</value>
      <webElementGuid>ed45395e-900d-451b-babe-5ba3b227e845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@data-automation='FAQ']/div</value>
      <webElementGuid>87525002-45aa-4cff-9fa6-f2c027cda27e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[5]/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div[2]/div/div[2]/a/div/span/span</value>
      <webElementGuid>1cb4c132-80c0-4277-9006-5dee36a1d200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::span[2]</value>
      <webElementGuid>ccdca729-2e18-41bc-a949-032cbf656382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::span[4]</value>
      <webElementGuid>053c7513-077d-40bd-abbb-e79787efefbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send feedback'])[1]/preceding::span[1]</value>
      <webElementGuid>ed72f4ba-50b4-4622-97e4-420fd70842ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Social'])[1]/preceding::span[3]</value>
      <webElementGuid>403ad70a-1998-4c63-ad47-81a8d5af9a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FAQ']/parent::*</value>
      <webElementGuid>9920a4f4-a329-4abd-b951-89326b72eb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div[2]/div/div[2]/a/div/span/span</value>
      <webElementGuid>2ba6db7f-5dc0-4498-8573-059926d7392f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'FAQ' or . = 'FAQ')]</value>
      <webElementGuid>98575729-d058-495f-bcb8-818205e31c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
