<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img-employers</name>
   <tag></tag>
   <elementGuidId>d3ac6cb1-0990-41b0-967a-db503ff3c3c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@aria-labelledby='horizontal-list-Top-employers']//a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.sx2jih0.OSxc8_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>578475d9-cd4f-416c-8dd2-66d0d5106f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 OSxc8_0</value>
      <webElementGuid>43b51df0-4827-4bc7-8e5b-bb02cc55b549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://teb.cdn.seekasia.com/sg/a598cce2d294e14366f08e6a902012062804f1d533017067c0c546efd9eb0d38.jpg</value>
      <webElementGuid>63c1aadf-f8bc-4181-8bef-274840a073b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SG - 20220401 - NTUC Health Co-operative Ltd - TEB</value>
      <webElementGuid>c67f45b2-c825-444f-988c-5d46a42580c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[@aria-labelledby='horizontal-list-Top-employers']//a</value>
      <webElementGuid>f16b7720-2ea9-45c4-97b5-6a4f4c72c88c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div[3]/div/div/div[2]/div[2]/div/div/div/div/section/div/div[2]/div/div/div/div/div/div/div/div/a/img</value>
      <webElementGuid>45a8e942-8463-4862-afef-3f06251329ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='SG - 20220401 - NTUC Health Co-operative Ltd - TEB']</value>
      <webElementGuid>e7105487-9093-4d0b-a663-1ecd5f9a73e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>a144becf-ee1b-48a2-976d-04fdc68282cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://teb.cdn.seekasia.com/sg/a598cce2d294e14366f08e6a902012062804f1d533017067c0c546efd9eb0d38.jpg' and @alt = 'SG - 20220401 - NTUC Health Co-operative Ltd - TEB']</value>
      <webElementGuid>c031fe54-53d6-4aee-bccd-e3e763b92e32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
