<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li-jobs-saved</name>
   <tag></tag>
   <elementGuidId>d9e39ec1-70fd-4c00-abb3-fcb2503dc645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@aria-labelledby='horizontal-list-Saved-jobs']//li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.MAKc9_0 > a.sx2jih0.sx2jihf._12fs6yk0 > div.sx2jih0.zcydq85u.zcydq856.zcydq8ey.zcydq8p.zcydq8n._3Yr-i_0.FZHZl_0.tjTv0_0.HATlR_0._18qlyvc14._18qlyvc17.zcydq832.zcydq835 > div.sx2jih0.zcydq8p.zcydq8n.zcydq856.zcydq8ey.R17W-_0 > div.sx2jih0.zcydq876.zcydq866.zcydq896.zcydq886.zcydq856.zcydq8f6.zcydq8p.zcydq8n.zcydq8eu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>65e5a012-0810-40f0-a89e-6018b48bd0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq876 zcydq866 zcydq896 zcydq886 zcydq856 zcydq8f6 zcydq8p zcydq8n zcydq8eu</value>
      <webElementGuid>ce2eda77-f3d2-483a-9f13-1e09f98f5d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quality EngineerOlea Global Pte. Ltd.OthersSGD 6K - 12K monthly4d ago</value>
      <webElementGuid>17e19c0f-bfc9-424a-ad38-859e223fa865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[@aria-labelledby='horizontal-list-Saved-jobs']//li</value>
      <webElementGuid>fa80ac2f-c879-419d-9aed-0344a27c1211</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div[3]/div/div/div/div[5]/div/section/div/div[2]/ol/li/a/div/div/div</value>
      <webElementGuid>07eb3b7b-207a-4997-8484-d9f730ee6cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved jobs'])[3]/following::div[4]</value>
      <webElementGuid>ddbf0176-8b6a-403f-a44c-9e163d766011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show more'])[1]/following::div[12]</value>
      <webElementGuid>713a845a-26b6-46f1-94e0-a85b5cd916fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/section/div/div[2]/ol/li/a/div/div/div</value>
      <webElementGuid>488f7a2f-1c9a-45b7-83ef-9225bee86672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Quality EngineerOlea Global Pte. Ltd.OthersSGD 6K - 12K monthly4d ago' or . = 'Quality EngineerOlea Global Pte. Ltd.OthersSGD 6K - 12K monthly4d ago')]</value>
      <webElementGuid>f9d54607-1ac5-4e6d-b368-de2c7d067dea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
