<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ckbox-part-time</name>
   <tag></tag>
   <elementGuidId>16501026-efc3-4d36-bf99-d050e7a7e8eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobTypes-part_time']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jobTypes-part_time</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14b6e04a-4fa4-47c8-ac5d-edfbd78c56c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih1 sx2jih6 sx2jih7 sx2jihc zcydq85e zcydq88 zcydq8h zcydq86 ajlqar1 ajlqar2</value>
      <webElementGuid>7ae7a7d2-b1b8-46ea-8c11-9eb07a80ad35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5bb5b1bb-9d0c-4aaf-b1b3-ec833165ee5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobTypes-part_time</value>
      <webElementGuid>1773a3e9-c856-4d1b-91de-e7de9bd15d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobTypes</value>
      <webElementGuid>70b402cf-d876-4bdd-9f9c-6d8c701549de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>53911592-a7d7-4e28-be36-8fc41eebbce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='jobTypes-part_time']</value>
      <webElementGuid>b9c80e7c-1600-4adf-9736-86caec4a842a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobTypes-part_time']</value>
      <webElementGuid>b3edd80d-1d17-4e09-9762-e3dda4018175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='srpSearchForm']/div/div/form/div/div[2]/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div/div/div/div/div[2]/label/div/div/div/input</value>
      <webElementGuid>4bf101d2-e51c-414f-837f-b53991faf50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/div/div/div/input</value>
      <webElementGuid>664c7dc1-9771-4333-a0a1-0683bec32494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'jobTypes-part_time' and @name = 'jobTypes']</value>
      <webElementGuid>f16280f9-edfd-4f7f-99e8-e21afe027dea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
