<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ckbox-temporary</name>
   <tag></tag>
   <elementGuidId>a38787be-cb23-4678-b055-ed4c2f2711f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobTypes-temporary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jobTypes-temporary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>408db776-ba5e-45f4-be8f-b5bb46c97f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih1 sx2jih6 sx2jih7 sx2jihc zcydq85e zcydq88 zcydq8h zcydq86 ajlqar1 ajlqar2</value>
      <webElementGuid>94710de6-13b0-4a02-b8a8-77bb8131a7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5c1e6b96-02a4-41f2-8d8a-fb6715e68960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobTypes-temporary</value>
      <webElementGuid>405196a0-b0cb-4544-9d6f-ad00da332efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobTypes</value>
      <webElementGuid>774490d2-1a51-4b5b-8b26-24650ad493e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6fe4d413-a30a-494e-b1ce-93a10edeab45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='jobTypes-temporary']</value>
      <webElementGuid>67fa549e-b746-4715-9239-dde586e9ce79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobTypes-temporary']</value>
      <webElementGuid>2df7c240-bbcc-4289-a78c-546dc1b9fdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='srpSearchForm']/div/div/form/div/div[2]/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/label/div/div/div/input</value>
      <webElementGuid>6ce29c07-6860-4eae-a869-1880cb41f35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/div/div/div/input</value>
      <webElementGuid>bba0d1ae-d5c0-4914-bb6e-afca8c58cb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'jobTypes-temporary' and @name = 'jobTypes']</value>
      <webElementGuid>6b228432-e739-4dd0-9a24-0b4701fc80b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
