<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ckbox-Receive promotions</name>
   <tag></tag>
   <elementGuidId>20ad6d92-c463-49e1-bf6a-742a0144d331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#promotion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='promotion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecae3a7f-de83-4aae-abb1-662ed4c4daa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promotion</value>
      <webElementGuid>b4f6cd88-b66c-4b0f-ade2-71b44bafa0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>promotion</value>
      <webElementGuid>95ef5444-77b6-4df4-a21c-a86b54b45ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4349de7f-ca61-474d-80b3-99aa8a0243c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='promotion']</value>
      <webElementGuid>40d9b803-60f6-43f7-8416-e5c1d2fc8e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='promotion']</value>
      <webElementGuid>b8395fad-1ad6-4114-a27a-e8dec3fc2877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='check_promotion']/label/input</value>
      <webElementGuid>9a78350d-2a47-49a4-8d60-c7ba10d0f7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>8e04991d-c93e-4249-b207-de060f071f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'promotion' and @name = 'promotion' and @type = 'checkbox']</value>
      <webElementGuid>38ad16cb-5bbc-45c8-b9d6-59ae90d8a44f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
