<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-Log In Now</name>
   <tag></tag>
   <elementGuidId>75bb7c72-29e3-4ce0-80cf-ed25a0253ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='login_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f341ed4-c666-4576-8c5a-0d063fb2f337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-resize</value>
      <webElementGuid>a143b410-f641-4582-8f38-8da5bd4a4651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_btn</value>
      <webElementGuid>5e556e9b-bd18-4af0-a124-0d03e8ac6945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login_btn</value>
      <webElementGuid>040c273c-c1a9-4649-9833-d3c6fda22cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9fe0e408-8b17-424e-832a-c5e1c1bc98cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://myjobstreet.jobstreet.com.my/home/login.php?site=my&amp;language_code=3</value>
      <webElementGuid>31fb6ec1-492d-43a5-a44e-c2b40876cc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In Now</value>
      <webElementGuid>fcee926c-9cb0-4fbc-884e-de7bb2c888ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='login_btn']</value>
      <webElementGuid>00211757-5239-4719-95f4-8bdb26249558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='login_btn']</value>
      <webElementGuid>c3461234-8c71-4c3c-9d75-ecf7670a92d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_sign_up']/div[9]/span[2]/a</value>
      <webElementGuid>470ace44-b01e-4dd3-bf0a-53ddc2ed0a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log In Now')]</value>
      <webElementGuid>84631fb1-0683-41e9-9120-f89d6ecac0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already a member?'])[1]/following::a[1]</value>
      <webElementGuid>2176ded0-3569-4fb7-bf12-37674c1ba293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::a[1]</value>
      <webElementGuid>84788108-5693-48df-aa83-fca6470896b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Use'])[1]/preceding::a[1]</value>
      <webElementGuid>b2804a89-3aaf-4907-a679-4a1e362b2c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::a[2]</value>
      <webElementGuid>1c58c4b1-8e30-4d60-ac5a-8bdab5e5d839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log In Now']/parent::*</value>
      <webElementGuid>ea86b6f1-f1a1-480f-81a7-6663fc3fceae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://myjobstreet.jobstreet.com.my/home/login.php?site=my&amp;language_code=3')]</value>
      <webElementGuid>4831827f-0ddc-434c-8495-3fd9990c7eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>6a6622b3-2f1c-4495-9526-3f2b7c4ac556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'login_btn' and @name = 'login_btn' and @type = 'submit' and @href = 'https://myjobstreet.jobstreet.com.my/home/login.php?site=my&amp;language_code=3' and (text() = 'Log In Now' or . = 'Log In Now')]</value>
      <webElementGuid>0f9988ce-0937-4cf3-9367-542431b0f1cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
