<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-clear-location</name>
   <tag></tag>
   <elementGuidId>46b2250a-d2c4-47f3-9d8a-60ec74e377c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='locationAutoSuggest-clearfield-clear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#locationAutoSuggest-clearfield-clear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c10f437-61b9-402e-bc19-184bdabafffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih7 zcydq87e zcydq86e zcydq89e zcydq88e zcydq87 zcydq85q zcydq85a zcydq84u zcydq8y zcydq8x zcydq85 zcydq8g2 zcydq84 zcydq8h _97fi8d0 _97fi8d5 _6gmmoo0 _16ycv5p0</value>
      <webElementGuid>8b9f03aa-47d3-414a-94bb-454af424d0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5519399f-9821-4059-bf0a-9ef88263909a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationAutoSuggest-clearfield-clear</value>
      <webElementGuid>772f423b-fd7e-4b2f-b37a-31c4f9b0c6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>0fe038af-5b28-4f65-a718-bc6e5f2532f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0b9799ee-1daf-4499-8a07-5c4496f08500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='locationAutoSuggest-clearfield-clear']</value>
      <webElementGuid>635b4ae1-bfa8-4b89-a8be-135947e54240</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='locationAutoSuggest-clearfield-clear']</value>
      <webElementGuid>79b630f8-42ff-4829-93eb-a40f9a47638f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div/div/div/div/div/div[2]/div/form/div/div/div[2]/div[2]/div/div/div/div/div/div/span[5]/span/div/div/button</value>
      <webElementGuid>cb56b755-e774-4371-9f68-8cfed24aa240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ngor - Others'])[1]/following::button[1]</value>
      <webElementGuid>34f1dc41-bfb5-4dce-8863-842263358d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggestions will appear below the field as you type'])[2]/preceding::button[1]</value>
      <webElementGuid>1f93459a-1958-4011-908e-534cca762bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Sketch.'])[1]/preceding::button[1]</value>
      <webElementGuid>4d7e5723-881f-4f7a-9725-08ca70862130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span[5]/span/div/div/button</value>
      <webElementGuid>ea2da18d-459d-4c87-b809-cda8b91dd889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'locationAutoSuggest-clearfield-clear']</value>
      <webElementGuid>77fbcf57-adac-43c4-8102-08ea75797fc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
