<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Search</name>
   <tag></tag>
   <elementGuidId>3c792250-dae3-4a99-9607-d549053a9186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-automation='searchSubmitButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sx2jih0.sx2jih7.zcydq85y.zcydq8p.zcydq85a.zcydq84u.zcydq8y.zcydq8x.zcydq85.zcydq8g2.zcydq84.zcydq8h._97fi8d0._97fi8d5._18qlyvc15._18qlyvc17.zcydq816.zcydq817</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4aae5a6b-c674-43eb-bded-7ee50f80407f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih7 zcydq85y zcydq8p zcydq85a zcydq84u zcydq8y zcydq8x zcydq85 zcydq8g2 zcydq84 zcydq8h _97fi8d0 _97fi8d5 _18qlyvc15 _18qlyvc17 zcydq816 zcydq817</value>
      <webElementGuid>6919f299-a675-47bf-8e02-3f23f90570c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7663b612-c53b-48dc-92ba-ed0c160d3a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>searchSubmitButton</value>
      <webElementGuid>efa9ba74-1b54-432b-84fe-ac69a5752b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>c240d5f9-2aea-45f1-9e79-b46e86f3e101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-automation='searchSubmitButton']</value>
      <webElementGuid>8d620708-1e4f-494e-8132-8aecbbb73ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>7db67611-6dc9-44cb-973c-346c1e526868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div/div/div/div/div/div[2]/div/form/div/div/div[2]/div[4]/button</value>
      <webElementGuid>d9696a67-7302-48de-826d-2404a10045c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Job Specializations'])[1]/following::button[1]</value>
      <webElementGuid>af82da8d-5d9d-4179-9acf-218ed1a7494d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Sketch.'])[1]/following::button[1]</value>
      <webElementGuid>4e4338ac-2e1c-4224-9f49-b372cbd44926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent searches'])[1]/preceding::button[1]</value>
      <webElementGuid>34424939-dc3a-478f-a5d2-c23a52eb0182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>09217f13-cf8d-455b-934f-db2dffca75ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>028691c8-4269-4aef-a959-98ff29b1c1f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
