<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-clear-search</name>
   <tag></tag>
   <elementGuidId>7337dfd5-9741-4ceb-b054-feaa5d9864ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchKeywordsField-clearfield-clear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchKeywordsField-clearfield-clear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>640b6b6e-69cf-4d3f-8652-3d9ab333dbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih7 zcydq87e zcydq86e zcydq89e zcydq88e zcydq87 zcydq85q zcydq85a zcydq84u zcydq8y zcydq8x zcydq85 zcydq8g2 zcydq84 zcydq8h _97fi8d0 _97fi8d5 _6gmmoo0 _16ycv5p0</value>
      <webElementGuid>c705edea-dbb5-4316-b24f-e46ddceab95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39d6730c-5186-445c-a616-2da6de5dd6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchKeywordsField-clearfield-clear</value>
      <webElementGuid>2df75df3-1f38-437d-ba28-bb6fc784c91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>447cb39d-040e-48fe-9869-09272b1506e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f2938078-22be-4f35-b756-480a8ad41ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>63e8854e-9661-4d98-bac1-8cf57d570e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='searchKeywordsField-clearfield-clear']</value>
      <webElementGuid>000a6d80-0e9a-460b-82dc-82d360ac72f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchKeywordsField-clearfield-clear']</value>
      <webElementGuid>017c2610-8ec8-4b49-9485-6ec21f89f0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div/div/div/div/div/div[2]/div/form/div/div/div[2]/div/div/div/div/div/div/div/div/span[5]/span/div/div/button</value>
      <webElementGuid>767c2858-b8b1-4b22-b5a0-cdbde4bd486e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qA Engineer'])[1]/following::button[1]</value>
      <webElementGuid>b25f66bd-95c1-483e-a158-463e82c9c5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qa engineer'])[1]/following::button[1]</value>
      <webElementGuid>8c432b09-56bc-4fda-b25d-37e6f244e8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggestions will appear below the field as you type'])[1]/preceding::button[1]</value>
      <webElementGuid>0e0969ee-fd51-44a9-adfe-83ae7fdc41f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggestions will appear below the field as you type'])[2]/preceding::button[2]</value>
      <webElementGuid>0773e51d-96d0-4ec1-a575-2bd0f2b780b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/button</value>
      <webElementGuid>7dc82467-6adb-4cdb-9a27-d6176633a2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'searchKeywordsField-clearfield-clear']</value>
      <webElementGuid>8a73a68f-656c-4a48-914f-b20ed29ac53a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
