<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-clear-search</name>
   <tag></tag>
   <elementGuidId>7337dfd5-9741-4ceb-b054-feaa5d9864ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchKeywordsField-clearfield-clear</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='searchKeywordsField-clearfield-clear']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='searchKeywordsField-clearfield-clear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f854adb9-af38-4e0a-bcb1-fe986fb83410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih7 zcydq87e zcydq86e zcydq89e zcydq88e zcydq87 zcydq85q zcydq85a zcydq84u zcydq8y zcydq8x zcydq85 zcydq8g2 zcydq84 zcydq8h _97fi8d0 _97fi8d5 _6gmmoo0 _16ycv5p0</value>
      <webElementGuid>7d9f6432-6a08-4fbf-a659-eacfe1d87d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ed04fa6-9f90-4867-99e9-a76dbf7db3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchKeywordsField-clearfield-clear</value>
      <webElementGuid>d64b13c0-f26e-4244-898e-39f547e324f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>5a04e40b-114f-4176-bdb1-9e7e940a87da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d0050880-aa08-47e6-9310-effe003de57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>91b58f41-9abd-4b8c-bd81-7423be505346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='searchKeywordsField-clearfield-clear']</value>
      <webElementGuid>cfe05b42-8360-4fb8-9b80-b71d3d69a290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='searchKeywordsField-clearfield-clear']</value>
      <webElementGuid>b53be8df-b004-47fd-a2b2-e98b7b2b1d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div/div/div/div/div/div[2]/div/form/div/div/div[2]/div/div/div/div/div/div/div/div/span[5]/span/div/div/button</value>
      <webElementGuid>2c5f2f33-6564-48f7-b475-e7f018da514c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qA Engineer'])[1]/following::button[1]</value>
      <webElementGuid>bce4f386-57f3-45d0-9b2b-50a7cd439726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qa engineer'])[1]/following::button[1]</value>
      <webElementGuid>462cb447-035f-4bc1-9377-812145ee6ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggestions will appear below the field as you type'])[1]/preceding::button[1]</value>
      <webElementGuid>192b5ac5-2c9e-47d0-b876-66ecc8a3dc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggestions will appear below the field as you type'])[2]/preceding::button[2]</value>
      <webElementGuid>5cfae685-740f-4fe6-a8db-3694d3ec8462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/button</value>
      <webElementGuid>34d869a6-937b-4566-a804-c44865b92855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'searchKeywordsField-clearfield-clear']</value>
      <webElementGuid>a9f6770c-84a4-4f14-ba54-21b141f6e160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
