<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ckbox-specializations</name>
   <tag></tag>
   <elementGuidId>6c34d8e9-1860-4154-abf7-bfd759dd2950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[contains(text(),'${specializationName}')])[2]/parent::label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Select-50-514</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67ddd367-38d6-4934-badc-bbcf9c98dd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih1 sx2jih6 sx2jih7 sx2jihc zcydq85e zcydq88 zcydq8h zcydq86 ajlqar1 ajlqar2</value>
      <webElementGuid>40d6e63a-0576-42ad-931b-0cd099ea038e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e8582d9b-2c06-4149-a811-fc180adffd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Select-50-514</value>
      <webElementGuid>5985cefa-895d-42a6-b4d3-ea52a8ce414c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5d33c7c-6b34-49f0-bbb4-52f34da7d5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(text(),'${specializationName}')])[2]/parent::label</value>
      <webElementGuid>bffb550b-c642-4f5c-98b2-0e32b4b72756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Select-50-514']</value>
      <webElementGuid>19d4ecec-fbf1-43b8-9718-9df8388a06b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div/div/div/div/div/div[2]/div/form/div/div/div[2]/div[3]/div/div/div[2]/div/div/label[15]/div/div/input</value>
      <webElementGuid>40d27a69-2ac8-4526-a571-c2e4981a13cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[15]/div/div/input</value>
      <webElementGuid>bf5ed6a1-e0aa-4110-9676-f58961256c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Select-50-514']</value>
      <webElementGuid>43358ff1-c769-4a21-9269-c740bce896fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
