<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-location</name>
   <tag></tag>
   <elementGuidId>9b9679ad-9b14-4e91-ba0a-81ea7d255aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='locationAutoSuggest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#locationAutoSuggest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48b33638-2553-48a7-b76c-c90773d071a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 sx2jih1 sx2jih6 sx2jih7 sx2jihc zcydq8p zcydq89i zcydq88i zcydq85u zcydq85 zcydq85a _3dxvbx0 _3dxvbx1 _18qlyvc0 _18qlyvc1y _18qlyvc1 _18qlyvca _18qlyvc22 _3dxvbx3 _18qlyvc14  zcydq832</value>
      <webElementGuid>cf36ea40-835f-47ba-9b51-da276a77f3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationAutoSuggest</value>
      <webElementGuid>aee0fdbb-6c5d-43b5-b961-e3668a54563a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>locationAutoSuggest-aria-description</value>
      <webElementGuid>4b1b7456-9708-4881-a55b-6ab0ad0f7364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>110ac8d9-24cc-49b9-b6c6-00b44d3cf057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>locationInputField</value>
      <webElementGuid>5264cfe2-2da1-4f6f-b45f-3b6cc5552e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>5d6d5d39-7772-49df-8d0c-444f4589edc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>51486fe1-108a-4dfc-9421-6b14782cae02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>locationAutoSuggest-menu</value>
      <webElementGuid>a1ef515c-5dc4-487f-a017-7a292ad51bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c685eb27-b2c6-4fee-abda-95f2e7acd59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>locationAutoSuggest-label</value>
      <webElementGuid>553716e8-2db7-4c41-a536-f291204b97c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>037eabed-d4f6-4994-b0aa-eb80efd52edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>92074837-fde0-4b85-ae7d-00bc0d2a12f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6e8f1f3-22c3-43e1-83f2-5d38e3c64a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Area, city or town</value>
      <webElementGuid>da54a93c-c319-4acb-9910-e15a9012444d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='locationAutoSuggest']</value>
      <webElementGuid>c68be435-a77d-4b1c-a261-58669ef94960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='locationAutoSuggest']</value>
      <webElementGuid>7d2680d7-74dd-407d-a57f-6891ba5af113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentContainer']/div/div/div/div/div/div/div[2]/div/form/div/div/div[2]/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>9627cc9c-2f4b-47d9-b0d4-f5287a1ae815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>00ab2a79-74e8-4854-a97a-ab6c0374dbdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'locationAutoSuggest' and @type = 'text' and @placeholder = 'Area, city or town']</value>
      <webElementGuid>c88d118e-8296-44fe-acf6-808cdfa6f8fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
