<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link-Employers</name>
   <tag></tag>
   <elementGuidId>8f56ffd6-2d54-45e5-946a-c36dd591891f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header_employer_link']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='header_employer_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header_employer_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4410e953-c20a-461a-86c4-84a3de1a6fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>employers pull-right</value>
      <webElementGuid>e69f19c3-2fdf-4d2e-ba0a-046118418c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header_employer_link</value>
      <webElementGuid>f629b146-d720-44b9-85f7-3ffab36dc1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.jobstreet.com.my/employers/</value>
      <webElementGuid>44ebe796-ef62-49ea-bf3a-e4a7b5ef0324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>_gaq.push(['_trackEvent', 'JSMY Personalized Homepage', 'Employers page clicked', 'New Header']);</value>
      <webElementGuid>56a81eb9-b63e-4730-9e65-5c00b70be789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Post a Job Ad: +603-­2176 0333</value>
      <webElementGuid>ecdaea70-90bf-4eb6-bbc5-5456530639d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9da1ed09-67a0-425f-8902-4af027fb144d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employers</value>
      <webElementGuid>447e3494-cd9e-41c9-a0d3-6b0832e088ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='header_employer_link']</value>
      <webElementGuid>a2180774-b74b-4d2d-bae3-d2a7f019b67b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='header_employer_link']</value>
      <webElementGuid>7c208eae-0664-422f-91ad-b2d6179115eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myjs_header']/div/div[2]/div/div/div[4]/a</value>
      <webElementGuid>f4aa4e87-9b36-4a17-83ba-bcf4a9232002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Employers')]</value>
      <webElementGuid>e14ec34f-06cc-4d02-a705-5c59f44e5e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced'])[1]/following::a[1]</value>
      <webElementGuid>4925c3c6-11de-47c1-a62e-4784a5a02c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classified Jobs'])[1]/following::a[4]</value>
      <webElementGuid>9f5c2e6d-0abc-41fe-894f-5d00e6c84a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate Sign Up'])[1]/preceding::a[1]</value>
      <webElementGuid>f0e4279c-9d12-4ec1-8bd7-9778b619223d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up for FREE to easily get job matches and apply'])[1]/preceding::a[1]</value>
      <webElementGuid>ee735b83-3a18-40e1-9eb8-e69023913dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employers']/parent::*</value>
      <webElementGuid>ea5f5a57-2d18-4b98-9e42-03ca33de380f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.jobstreet.com.my/employers/')]</value>
      <webElementGuid>75a4a707-fbcf-4c27-984c-ac39e4f29d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>cd2a18ed-6540-47c7-b2bb-55b7b24cc7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'header_employer_link' and @href = 'https://www.jobstreet.com.my/employers/' and @title = 'Post a Job Ad: +603-­2176 0333' and (text() = 'Employers' or . = 'Employers')]</value>
      <webElementGuid>2c6c7e35-254f-462c-9325-dabb882b6bf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
