<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-search</name>
   <tag></tag>
   <elementGuidId>0faee6c9-83d5-404d-89bd-03c5d4c86beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header_searchbox_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header_searchbox_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>413b3ab6-b523-473f-b39e-737a8f975c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header_searchbox_btn</value>
      <webElementGuid>7141124a-db78-4786-8e82-bd69894a00e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>a28f946f-c8fe-48a8-b396-769ffee3b917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18130465-3697-4fa6-a732-426582c5eb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>_gaq.push(['_trackEvent', 'JSMY Personalized Homepage', 'Search button clicked', 'New Header']);</value>
      <webElementGuid>78f1132a-6e74-41b0-a7f4-3df582be3639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='header_searchbox_btn']</value>
      <webElementGuid>e9ffe029-ad56-48b6-b2ce-bfee1cc8d487</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='header_searchbox_btn']</value>
      <webElementGuid>9eff2519-63e7-40a0-a475-86cfec3964f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSearch']/div/span/a</value>
      <webElementGuid>c9935b62-dd5a-4e00-9faf-586e483888ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classified Jobs'])[1]/following::a[2]</value>
      <webElementGuid>2ba2598b-f1a4-4912-b346-7ce33183e96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fresh Grad Jobs'])[1]/following::a[3]</value>
      <webElementGuid>5ad4e8f4-49bc-4a57-9b9f-91f1d7c7817e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced'])[1]/preceding::a[1]</value>
      <webElementGuid>aee02e1b-427c-4917-adc3-8acb47e08f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employers'])[1]/preceding::a[2]</value>
      <webElementGuid>cbd0d68e-b274-45f8-a957-77442391eee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/span/a</value>
      <webElementGuid>672a703c-2d6f-4605-a21e-451dd22c5641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'header_searchbox_btn' and @type = 'button']</value>
      <webElementGuid>fcb6c179-2b9d-4e40-a796-dbc218fcb910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
