<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img-logo</name>
   <tag></tag>
   <elementGuidId>a6292227-1f60-4630-9712-feb598d1e5e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header_logo_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header_logo_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a613729-b46e-4cd5-b527-57db64b53965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-logo-js logo-my</value>
      <webElementGuid>c1d9900e-f950-491a-8654-52adeb85951a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header_logo_link</value>
      <webElementGuid>2cc0339a-4d4c-4061-952c-63773ea29724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.jobstreet.com.my</value>
      <webElementGuid>f0d9326c-a8d7-40fb-ae26-3c9a2f58dc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Leading Job Site in Malaysia - Find Jobs, Advertise Jobs in Malaysia</value>
      <webElementGuid>1cdbf9c5-8685-491a-8c6c-3bc7321e1f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>JobStreet.com - Malaysia</value>
      <webElementGuid>23542a32-acef-4410-ada4-0a0c25bb6b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>36dc1365-643f-4157-920b-c9cfefc55f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='header_logo_link']</value>
      <webElementGuid>f94c15b7-79b1-49c6-bce4-1bf3992616f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='header_logo_link']</value>
      <webElementGuid>22d93229-fad5-4685-b5ae-dd351bd60645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myjs_header']/div/div[2]/div/div/div/a</value>
      <webElementGuid>767c6fbc-eaad-43df-ab57-f69645e4d312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.jobstreet.com.my')])[8]</value>
      <webElementGuid>09905acb-6328-44ba-8ebc-5493945d8809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>e621d13c-beff-4168-aff4-412ecb141b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'header_logo_link' and @href = 'https://www.jobstreet.com.my' and @title = 'Leading Job Site in Malaysia - Find Jobs, Advertise Jobs in Malaysia' and @alt = 'JobStreet.com - Malaysia']</value>
      <webElementGuid>c7157f87-3601-4772-b3d6-2741f60ba1d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
