<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-email</name>
   <tag></tag>
   <elementGuidId>ffc494de-5dad-4d5d-9058-e8fcb788abdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fdef380-b9dd-4cf2-9129-1eb7ba765a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>46c9729a-2fef-44a8-8bbd-d38897459c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_id</value>
      <webElementGuid>ef76a948-e65c-4262-83b6-71a2038b8924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login_id</value>
      <webElementGuid>32a3c3d2-8cd4-4d7c-8b58-e47b984aef1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73a3c7e9-2574-47d2-b8a0-5be1b56fb91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>5e7a61ee-2c5d-4747-bacb-c94b33c57361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='login_id']</value>
      <webElementGuid>76a92135-2594-445b-a81d-6634cbc22a15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_id']</value>
      <webElementGuid>f646d3e4-0245-49e3-bb3b-1d3cf044483f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login_id_form']/input</value>
      <webElementGuid>8e721687-44c6-4097-89e5-65cf68cc452f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/form/div/input</value>
      <webElementGuid>05a5fd49-9a2a-45e7-b1bb-49bfc4e5c7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login_id' and @name = 'login_id' and @type = 'text' and @placeholder = 'Email']</value>
      <webElementGuid>c85e32e2-31bb-491f-848a-1ca887ff6ceb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
