<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-search-jobs</name>
   <tag></tag>
   <elementGuidId>4ffdda91-92f4-4685-9a11-f698238b42a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_box_keyword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_box_keyword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7304c8ae-7117-4d79-8616-371a8f438fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_box_keyword</value>
      <webElementGuid>2d461671-bed3-4d76-9cbb-41e2a297925d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>4c1114d1-f7db-4847-ac24-de8a7460175c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>414b3dc2-84c5-440d-a95c-1d3be6fac48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Jobs By Title, Skills or Keywords...</value>
      <webElementGuid>1a9b4155-90a2-42a6-8b85-cdb9bc5974c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>323c1e46-fd10-4572-81e8-f72eecf7f466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='search_box_keyword']</value>
      <webElementGuid>3dcb3cb9-c7f6-4742-9cee-3fe9f063010b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_box_keyword']</value>
      <webElementGuid>f59e1d83-b1fa-4d01-ad2f-dd1e6922d86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSearch']/div/input[2]</value>
      <webElementGuid>d6e9d4d9-1865-4064-a4dd-c742823d3bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/input[2]</value>
      <webElementGuid>1f29bd2d-c1b9-405a-8d0f-5a9c894af0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search_box_keyword' and @name = 'key' and @type = 'text' and @placeholder = 'Search Jobs By Title, Skills or Keywords...']</value>
      <webElementGuid>573a409e-af6b-4502-86bb-faf2319488ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
