<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slider-min</name>
   <tag></tag>
   <elementGuidId>00c03760-4050-44b4-9c34-45293ba84b1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation='rangeSliderMin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sx2jih0.rc-slider-handle.rc-slider-handle-1.FpChI_0.alDry_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a05b098-0a9e-4952-80e8-1842a14358ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 rc-slider-handle rc-slider-handle-1 FpChI_0 alDry_0</value>
      <webElementGuid>bcd9c7fb-12aa-41a0-8b94-1d87c50ac0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>rangeSliderMin</value>
      <webElementGuid>a13c071d-c5ca-45d8-85e0-dd162a062688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Min</value>
      <webElementGuid>0295eb9b-432b-4c20-8b98-7e9003ce1680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation='rangeSliderMin']</value>
      <webElementGuid>404f1e9f-5546-4d97-a30a-b5408cee07c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rangeContainer']/div/div/div[4]</value>
      <webElementGuid>ab7d468b-6e32-4639-b7d0-1b6a814176fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGD 22K+'])[1]/following::div[11]</value>
      <webElementGuid>627fac29-70f8-433e-be44-eefee5458f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='to'])[1]/following::div[11]</value>
      <webElementGuid>54529bdf-d4d5-4652-9891-e76df31a89b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max'])[1]/preceding::div[2]</value>
      <webElementGuid>9f5b7feb-ff1b-4864-afb9-6a8f56f744ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div/div/div[4]</value>
      <webElementGuid>bcc9fa66-79c2-43bd-9c83-73664fd9cab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Min' or . = 'Min')]</value>
      <webElementGuid>a68654d2-18b8-4237-88fe-28f3932534b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
