<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slider-max</name>
   <tag></tag>
   <elementGuidId>c4912d1e-e545-46f4-aeec-8c8a62dbf485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-automation='rangeSliderMax']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sx2jih0.rc-slider-handle.rc-slider-handle-2._0qvB6_0.alDry_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3344a1c2-a141-44f3-98c2-6b2966dc4b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 rc-slider-handle rc-slider-handle-2 _0qvB6_0 alDry_0</value>
      <webElementGuid>3c44bc10-26cd-4908-a81f-35ac28b110e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>rangeSliderMax</value>
      <webElementGuid>61c98306-2cc1-4a52-8a1b-46302add35a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Max</value>
      <webElementGuid>69f9e4bc-e273-43ee-a96a-32e79d0cffbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation='rangeSliderMax']</value>
      <webElementGuid>cdae5596-38df-4d61-9ce8-e05764615ff1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rangeContainer']/div/div/div[5]</value>
      <webElementGuid>990103b5-643c-4f6f-85a8-4c24d6448fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Min'])[1]/following::div[1]</value>
      <webElementGuid>2db5e5a0-7940-48e9-9dc3-432a96ba7ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGD 22K+'])[1]/following::div[13]</value>
      <webElementGuid>5aafa776-f408-480a-8c9c-293d49ee7642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::div[6]</value>
      <webElementGuid>cdc00f06-9d9a-47fe-a485-c99200a2ca2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[5]</value>
      <webElementGuid>1f9236c2-d8c5-449b-9533-f5a0259b5360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Max' or . = 'Max')]</value>
      <webElementGuid>5f90abac-1982-4cbd-ac71-9c22cb64f8c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
